### ISSUE TITLE
[Stable 1.0.2] Unusable with Android 11: Toast.getView() is deprecated

### ISSUE THREAD

**Issue by JohannesHC** [developermypos/myPOS-SDK-Android#12]
With Android 11 (API Level 30) `toast.getView()` was deprecated ([see documentation](https://developer.android.com/reference/android/widget/Toast?hl=en#getView()))

This leads to a NullpointerException when calling `POSHandler.getInstance()` making the whole SDK unusable on Android 11.

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.mypos.slavesdk.POSHandler.setDefaultInfoListener(POSHandler.java:180)
        at com.mypos.slavesdk.POSHandler.<init>(POSHandler.java:170)
        at com.mypos.slavesdk.POSHandler.getInstance(POSHandler.java:147)
```

**Comment by developermypos** [comment]
Hi,

Please try our beta version. This and other issues are fixed there.

implementation 'com.mypos:slavesdk-beta:2.0.7'

**Comment by JohannesHC** [comment]
It works with the beta version, but I don't want to use a 2-year-old beta in a production environment.

Looking at the commit history, this bug was fixed in the beta version about 5 months ago.
Why was this critical bug not fixed in the stable release?

**Comment by developermypos** [comment]
The 'beta' version is stable enough, so we are planning to merge it to the 'master' very soon.
